Before: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> (Greek: Ἱστορίαι**
Before: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> (431–404**
Before: (War I)  -->  **the Trojan <span style='color: red'>War</span>. For instance**
Before: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> broke out**
Before: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> to the**
Before: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span>, it uses**
After: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> was the**
After: (War I)  -->  **the Peloponnesian <span style='color: red'>War</span> not because**
